/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'jresendiz' at '8/28/16 7:41 PM' with Gradle 2.14.1
 *
 * @author jresendiz, @date 8/28/16 7:41 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
