/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'jresendiz' at '8/28/16 7:41 PM' with Gradle 2.14.1
 *
 * @author jresendiz, @date 8/28/16 7:41 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
